### ISSUE TITLE
Create sim data for Carl

### ISSUE THREAD

**Issue by richelbilderbeek** [richelbilderbeek/gcaer#2]
Depends on:

 * [x] [plinkr: Allow to do 'assoc_qt' with PLINK1 binary data](https://github.com/richelbilderbeek/plinkr/issues/16)
 * [x] [plinkr: Allow to do 'assoc_qt' with PLINK1 binary data and a phenotype file](https://github.com/richelbilderbeek/plinkr/issues/17)

Created simulated data in PLINK1 format that has genetic data as well as phenotypes, as requested by @cnettel .

**Comment by richelbilderbeek** [comment]
Must be PLINK1 binary format, as that is what GCAE uses now.

**Comment by richelbilderbeek** [comment]
This is a good start:

```
# Create sim data for Carl
# https://github.com/richelbilderbeek/gcaer/issues/2
#
# Output must be in PLINK binary format
#
#
#

library(plinkr)

# Simulate data in PLINK1 text format
assoc_qt_params <- create_demo_assoc_qt_params(
  n_individuals = 1000,
  traits = create_demo_traits()
)

# Convert PLINK1 text format to PLINK1 binary format
base_input_filename <- "~/issue_2_text"
ped_filename <- paste0(base_input_filename, ".ped")
map_filename <- paste0(base_input_filename, ".map")
phe_filename <- paste0(base_input_filename, ".phe")
base_output_filename <- "~/issue_2_bin"
plinkr::save_ped_table_to_file(
  ped_table = assoc_qt_params$ped_table,
  ped_filename = ped_filename
)
plinkr::save_map_table_to_file(
  map_table = assoc_qt_params$map_table,
  map_filename = map_filename
)
plinkr::save_phe_table_to_file(
  phe_table = assoc_qt_params$phe_table,
  phe_filename = phe_filename
)
plink_bin_filenames <- plinkr::convert_plink_text_files_to_plink_bin_files(
  base_input_filename = base_input_filename,
  base_output_filename = base_output_filename
)

# Done!

# But hey, if you want to inspect the data:
bim_table <- read_plink_bim_file(plink_bin_filenames$bim_filename)
fam_table <- read_plink_fam_file(plink_bin_filenames$fam_filename)
bed_table <- read_plink_bed_file(
  bed_filename = plink_bin_filenames$bed_filename,
  names_loci = bim_table$id,
  names_ind = fam_table$id
)

plinkr::read_plink_bed_file(plink_bin_filenames$bed_filename)
```

Problem is that the phenotypes are not in PLINK1 binary format. Maybe they need not be, as PLINK can do a quantitative association on the 3 PLINK1 binary files **with** the phenotype file. Checking now!

**Comment by richelbilderbeek** [comment]
Sent to Carl:

> Attached is what I think you want, yet I am still checking if I am correct [1]. The files are simulated PLINK binary data files, including the phenotypes in 'issue_2_bin.phe'.

[issue_2_bin.zip](https://github.com/richelbilderbeek/gcaer/files/7193861/issue_2_bin.zip)

# Background

I created `issue_2_bin.phe` by renaming it from `issue_2_text.phe`. To be sure if this works, I need to [do 'assoc_qt' with PLINK1 binary data](https://github.com/richelbilderbeek/plinkr/issues/16).

**Comment by cnettel** [comment]
The phe file is seemingly missing from the zip. The pheno column in the ped file seems to be all zeros.

**Comment by richelbilderbeek** [comment]
@cnettel blimey, I zipped the wrong files, here they are:

[issue_2_bin.zip](https://github.com/richelbilderbeek/gcaer/files/7195380/issue_2_bin.zip)

Enjoy!

**Comment by richelbilderbeek** [comment]
I confirmed the data is correct :-)

It should be a .bed, .bim, .fam and .phe file.
